# Imporing Libraries

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing data

In [27]:
data = pd.read_csv(r"C:\Users\yaksh\OneDrive\Desktop\programing\ML\ML data\Dataset_master.xlsx - Instagram Ads SVM.csv")
data.head()

Age  Mobile Phone  Purchased
0   15          6334          0
1   28          6667          0
2   20         14334          0
3   21         19000          0
4   15         25334          0

In [28]:
X=data.iloc[:,0:2].values
Y=data.iloc[:,-1:].values

In [29]:
print(X)

[[   15  6334]
 [   28  6667]
 [   20 14334]
 [   21 19000]
 [   15 25334]
 [   21 19334]
 [   21 28000]
 [   25 50000]
 [   20 11000]
 [   28 21667]
 [   20 26667]
 [   26 17000]
 [   28 36000]
 [   18  6667]
 [   20 26334]
 [   21 18000]
 [   24 45000]
 [   24 29667]
 [   19 10667]
 [   14 14667]
 [   23 27667]
 [   28  7667]
 [   21 19334]
 [   19 18334]
 [   18 16000]
 [   22 26334]
 [   17  6000]
 [   25 39000]
 [   21  6667]
 [   20 29000]
 [   18 22000]
 [   25 40000]
 [   17 21000]
 [   24 22667]
 [   20 26667]
 [   19  9000]
 [   16  7667]
 [   26 37667]
 [   25  6000]
 [   27 37334]
 [   24 38667]
 [   20  5000]
 [   23  9334]
 [   23 27667]
 [   26 49667]
 [   15  7000]
 [   16 24000]
 [   20 11667]
 [   21 29667]
 [   20 28667]
 [   30 26667]
 [   31 23667]
 [   29 23667]
 [   20 30000]
 [   29 11000]
 [   17 18334]
 [   28 23667]
 [   23 49334]
 [   23 15667]
 [   16 29334]
 [   27 38334]
 [   20 39334]
 [   27 14334]
 [   27 24000]
 [   18  9334]
 [   28 15667]
 [   20  7

In [30]:
print(Y)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]]


# Spliting Data

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=21)

In [32]:
print(X_train)

[[   31 44667]
 [   26 49667]
 [   36 27334]
 [   32 17334]
 [   29 20667]
 [   28 20000]
 [   25 50000]
 [   48 36000]
 [   41  7000]
 [   39 47000]
 [   37 48000]
 [   38 10000]
 [   44 13000]
 [   41 38000]
 [   28 20334]
 [   33 26334]
 [   15  6334]
 [   32 26334]
 [   20 26667]
 [   29 17334]
 [   28 18000]
 [   16 27334]
 [   32 26000]
 [   20 26667]
 [   32 20000]
 [   32 20334]
 [   37 35667]
 [   45 20000]
 [   38 39667]
 [   20  5000]
 [   36 10667]
 [   34 44334]
 [   16 24000]
 [   25  6000]
 [   37 14334]
 [   21 19000]
 [   20 29000]
 [   23 14334]
 [   40 12000]
 [   42 47667]
 [   16  7667]
 [   17 18334]
 [   24 26334]
 [   28 20000]
 [   26 17000]
 [   32 25000]
 [   20 28667]
 [   41 46000]
 [   20 26667]
 [   28 15667]
 [   45 40667]
 [   19  7667]
 [   28 13000]
 [   32 47334]
 [   28 19334]
 [   15 23334]
 [   37 15667]
 [   39 29334]
 [   25 40000]
 [   17 21000]
 [   29 31000]
 [   45  8667]
 [   25 39000]
 [   28 32334]
 [   31 23667]
 [   28  6667]
 [   47 47

In [33]:
print(X_test)

[[   48 14000]
 [   28 21667]
 [   24 29667]
 [   23 27667]
 [   15  7000]
 [   21 28000]
 [   29 23667]
 [   38 32000]
 [   29 48667]
 [   42 27334]
 [   28  7667]
 [   23  9334]
 [   29 17667]
 [   31 35334]
 [   44 43334]
 [   47 29334]
 [   32 17334]
 [   41 50000]
 [   28 30334]
 [   18  6667]
 [   32 24000]
 [   22 29667]
 [   24 38667]
 [   37 16667]
 [   33 21667]
 [   32 21667]
 [   31 44667]
 [   33 49667]
 [   20 14334]
 [   32 24000]
 [   14 14667]
 [   47 25334]
 [   45 24667]
 [   21 19334]
 [   29 48000]
 [   27 38334]
 [   28 24000]
 [   33 24334]
 [   33 36000]
 [   29 11000]
 [   31 26334]
 [   31 14000]
 [   29 26667]
 [   20 26334]
 [   28 42000]
 [   46 33667]
 [   28 21000]
 [   28 26334]
 [   17  6000]
 [   28 48000]
 [   16 12000]
 [   41 12667]
 [   22 10667]
 [   36 39000]
 [   26 37667]
 [   27 14334]
 [   29 25667]
 [   23 27667]
 [   19 18334]
 [   41 30000]]


In [34]:
print(Y_train)

[[1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]]


In [35]:
print(Y_test)

[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]


# Feature Scaling

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# ML algorithm

In [40]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=21)
classifier.fit(X_train,Y_train)

C:\Users\yaksh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=21)

# Prediction

In [42]:
print(classifier.predict(sc.transform([[25,44500]])))

[1]


In [43]:
a=classifier.predict(X_test)
a=a.reshape(len(a),1)
b=Y_test
b=b.reshape(len(b),1)
print(np.concatenate((b,a),1))

[[1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]


In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(b,a))
print(confusion_matrix(b,a))

0.9333333333333333
[[37  0]
 [ 4 19]]
